// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:00348651-5517-4109-a264-4d537766447d',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'bubble-hosting-mobilehub-69251676',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1whjwftcvbppz.cloudfront.net',
    'aws_mobile_analytics_app_id': '94c98a90a3b440d28bdd8e14287cb95b',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e4032bd2-328d-43a5-9970-c86792509d5e',
    'aws_project_name': 'bubble-2019-01-02-21-09-19',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'bubble-mobilehub-69251676',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_1z7Ri0bqt',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '76uutrmk823cjeaep8q75e0ai6',
}

export default awsmobile;
