// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:a25b3899-eb75-4620-8772-44000fd49d1f',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'bubble-hosting-mobilehub-876048438',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd6r17pene356f.cloudfront.net',
    'aws_mobile_analytics_app_id': '72db6087ec5f4f2aadd966ca814fd1ee',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '70e8a509-6a63-42c3-a00d-fecbda875cbd',
    'aws_project_name': 'bubble-2019-01-02-19-51-04',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'bubble-mobilehub-876048438',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_mO1rgAVfZ',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '2ormivo2peh32rsfjf1kovgh6q',
}

export default awsmobile;
